config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy

  validates :name, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :company
  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  # Trational way to broadcast
  # after_create_commit -> { broadcast_prepend_to 'quotes', partial: 'quotes/quote', locals: { quote: self}, target: 'quotes' }
  # after_create_commit -> { broadcast_prepend_to 'quotes'} # Using the convetion rails to broadcast
  # after_update_commit -> { broadcast_replace_to 'quotes'}
  # after_destroy_commit -> { broadcast_remove_to 'quotes'}

  # Using the activeJob to broadcast
  # after_create_commit -> { broadcast_prepend_later_to 'quotes'}
  # after_update_commit -> { broadcast_replace_later_to 'quotes'}
  # after_destroy_commit -> { broadcast_remove_to 'quotes'}

  # Alias to CRUD actions broadcast
  broadcasts_to ->(quote) { [quote.company, 'quotes'] }, inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable
  belongs_to :company

  def name
    email.split('@').first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end

  helper_method :current_company

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[company_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  before_action :set_quote, only: %i[show edit update destroy]

  def index
    @quotes = current_company.quotes.ordered
  end

  def show; end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: 'Quote was successfully created.' }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @quote.update(quote_params)
      redirect_to quotes_path, notice: 'Quote was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.turbo_stream
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

# devise helper
module DeviseHelper
  def devise_error_messages!
    return if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg|
      content_tag(:p, "- #{msg}.")
    }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
      <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <p>#{sentence}</p>#{messages}
      </div>
    HTML

    html.html_safe
  end

  def devise_simple_error_messages!
    return if resource.errors.empty?

    sentence = "Ooops!"
    if resource.errors.count == 1
      message =  resource.errors.full_messages[0]
      html = <<-HTML
        <div class="bg-red-lightest border-l-4 border-red text-orange-dark p-4" role="alert">
          <p class="font-bold">#{sentence}</p>
          <p> #{ message }.</p>
        </div>
      HTML
    else
      messages = resource.errors.full_messages.map { |msg|
        content_tag(:li, "#{msg}.")
      }.join
      html = <<-HTML
        <div class="bg-red-100 border-l-4 border-red-500  mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">#{sentence}</p>
          <ul class="list-disc">
            #{messages}
          </ul>
        </div>
      HTML
    end

    html.html_safe
  end
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/views/layouts/_navbar.html.slim
- if user_signed_in?
  header
    nav class='w-full flex justify-between items-center py-4'
      div class='items-center'
        h2 class='text-2xl font-semibold'
          = current_company.name
      div class='flex items-center space-x-3'
        span class='text-medium font-semibold text-gray-500 letter-spacing-wide'
          | @#{ current_user.name }
        = button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn--primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title w3n templates
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body class='container mx-auto px-4 bg-gray-50 text-sm h-screen'
    = render 'layouts/navbar'
    main class='mx-auto md:w-2/4 h-96'
      = yield

app/views/pages/home.html.slim
section class='flex flex-col items-center justify-center min-h-full'
  h1 class='text-6xl mb-2' Quote editor
  p class='text-xl font-light' A blazing fast quote editor built with Hotwire

  div class='mt-10'
    - if user_signed_in?
      = link_to 'View Quotes', quotes_path, class: 'btn btn--primary'
    - else
      = link_to 'Sign in', new_user_session_path, class: 'btn btn--primary'

app/views/quotes/_form.html.slim
div class='bg-white shadow rounded-lg p-4 mb-3 border border-gray-50'
  = simple_form_for quote, html: { class: 'quote form' } do |f|
    - if quote.errors.any?
      div class='error-message bg-red-50 rounded-lg p-2 text-sm font-medium mb-2 items-center'
        = heroicon 'exclamation-triangle', options: { class: 'h-4 w-4 text-red-500 inline-block mr-1 ml-2' }
        = quote.errors.full_messages.to_sentence.capitalize
    div class='flex justify-between items-center space-x-2'
      div class='flex-1'
        = f.input :name, label: false, input_html: { autofocus: true, class: 'w-full rounded border-gray-300 placeholder:text-gray-400 placeholder:text-sm', placeholder: 'Name of your quote ...' }
      = link_to quotes_path, class: 'btn text-black p-2 hover:text-black' do
        - if action_name == 'new'
          = heroicon 'x-mark', options:{ class: 'w-5 h-5' }
        - else
          = heroicon 'arrow-uturn-left', options:{ class: 'w-5 h-5' }
      = f.button :button, class: 'btn text-white bg-green-500 p-2' do
        = heroicon 'check', options:{ class: 'w-5 h-5' }

app/views/quotes/_quote.html.slim
= turbo_frame_tag quote do
  div class='quote flex justify-between items-center bg-white shadow rounded-lg p-4 mb-3 border border-gray-50'
    div class='flex-1'
      = link_to quote.name, quote_path(quote), data: { turbo_frame: '_top' }
    div class='quote__actions flex space-x-2'
      = button_to quote_path(quote), method: :delete, class:'btn text-black p-2 inline-block' do
        = heroicon 'trash', options:{ class: 'w-5 h-5' }
      = link_to edit_quote_path(quote), class:'btn text-black p-2 hover:text-black' do
        = heroicon 'pencil-square', options:{ class: 'w-5 h-5' }

app/views/quotes/create.turbo_stream.slim
= turbo_stream.prepend 'quotes', @quote
= turbo_stream.update Quote.new, ''

app/views/quotes/destroy.turbo_stream.slim
= turbo_stream.remove @quote

app/views/quotes/edit.html.slim
section
  = link_to sanitize("&larr; Back to quotes"), quote_path(@quote)

  header
    h1 Edit Quote

  div
    = turbo_frame_tag @quote do
      = render 'form', quote: @quote

app/views/quotes/index.html.slim
= turbo_stream_from current_company, 'quotes'

section class='mt-10'
  header class='flex justify-between items-center mb-4'
    h1 Quotes
    = link_to 'New Quote', new_quote_path, class:'btn btn--primary', data: { turbo_frame: dom_id(Quote.new) }

  = turbo_frame_tag Quote.new

  div class='mt-10'
    = turbo_frame_tag 'quotes' do
      =render @quotes

app/views/quotes/new.html.slim
section
  = link_to sanitize("&larr; Back to quotes"), quotes_path

  header
    h1 class='mb-4' New Quote

  div
    = turbo_frame_tag @quote do
      = render 'form', quote: @quote

app/views/quotes/show.html.slim
section
  = link_to sanitize("&larr; Back to quotes"), quotes_path
  header
    h1 = @quote.name